//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UserConsole.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_USERCONSOLE_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_MAINFORM             130
#define IDD_DIALOG_RECHARGECARD         132
#define IDD_DIALOG_RECHARGECARDLOG      134
#define IDD_DIALOG_USERCONFIG           136
#define IDD_DIALOG_CONFIG_FIELD         138
#define IDD_DIALOG_CONFIG_COLLECT       140
#define IDD_DIALOG_CONFIGMODE           142
#define IDD_DIALOG_READCONFIG_OTHERPLAYER 148
#define IDC_EDIT_ACCOUNT                1000
#define IDC_EDIT_PASS                   1001
#define IDC_BUTTON_LOGIN                1002
#define IDC_BUTTON_REGISTER             1003
#define IDC_BUTTON_RECHARGECARD         1003
#define IDC_BUTTON_RUNGAME              1005
#define IDC_BUTTON_RECHARGECARDLOG      1006
#define IDC_STATIC_HOUR                 1007
#define IDC_EDIT_CARD                   1008
#define IDC_BUTTON_SUMIT_RECHARGE       1009
#define IDC_EDIT_CARDLOG                1010
#define IDC_TAB1                        1011
#define IDC_CHECK_USEEXORCISM           1016
#define IDC_EDIT_FIELD_PERSON_HP        1017
#define IDC_CHECK_AUTOBUY_PETDRINK      1017
#define IDC_EDIT_FIELD_PET_HP           1018
#define IDC_COMBO_FIELD_PERSON_FIGHTMODE 1019
#define IDC_EDIT_FIELD_PET_MP           1020
#define IDC_EDIT_FIELD_PERSON_MP        1021
#define IDC_COMBO_FIELD_PET_FIGHTMODE   1022
#define IDC_CHECK_AUTOBUY_EXORCISM      1023
#define IDC_CHECK_AUTOBUY_HAPPYBELL     1024
#define IDC_COMBO_CONFIGMODE            1025
#define IDC_BUTTON_RUN                  1026
#define IDC_BUTTON_STOP                 1027
#define IDC_CHECK_FIELD_DEFAULTCONFIG   1028
#define IDC_BUTTON_FIELD_SUMIT          1030
#define IDC_EDIT_COLLECT_PETDRINK_COUNT 1032
#define IDC_CHECK_COLLECT_ITEMNAME_RES  1033
#define IDC_CHECK_COLLECT_ITEMNAME_REDBEAD 1034
#define IDC_COMBO_COLLECT_MAP           1035
#define IDC_RADIO_COLLECT_FURNITURE1    1038
#define IDC_BUTTON_COLLECT_SUMIT        1039
#define IDC_CHECK_COLLECT_DEFAULTCONFIG 1040
#define IDC_RADIO_COLLECT_FURNITURE2    1041
#define IDC_RADIO_COLLECT_FURNITURE3    1042
#define IDC_RADIO_COLLECT_FURNITURE4    1043
#define IDC_BUTTON_COLLECT_READCONFIG_OTHERPLAYER 1051
#define IDC_BUTTON_FIELD_READCONFIG_OTHERPLAYER 1052
#define IDC_EDIT_PLAYERNAME             1053
#define IDC_BUTTON_READCONFIG           1054

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
